name: Build Windows Executable

on:
  push:
    branches: [rewrite]

    paths:
      - 'host/**'
      - '.github/workflows/nuitka.yml'

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# env: nxdt_commit: ${GITHUB_SHA::7}

jobs:
  build:
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh
        # working-directory: .\host

    steps:
      - name: Set environment variables.
        run: "nxdt_commit=${GITHUB_SHA::7}" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
            # 3.12.5 was released on 2024-08-06.
            # See https://www.python.org/downloads/ for available versions.

      - name: Install dependencies and build EXE
        run: .\host\windows_make_standalone.bat

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: nxdt_host-${{ env.nxdt_commit }}
          path: host/nxdt_host.7z
          if-no-files-found: error

      - name: Upload nxdumptool-rewrite PoC artifacts to pre-release
        uses: ncipollo/release-action@v1
        with:
          # Only update attachments on "rewrite-prerelease" tag.
          prerelease: True
          tag: "rewrite-prerelease"
          updateOnlyUnreleased: True
          # Remove old artifacts and replace with new ones.
          removeArtifacts: False
          replacesArtifacts: True
          # Update preferences.
          allowUpdates: True
          omitBody: True
          omitBodyDuringUpdate: True
          omitNameDuringUpdate: True
          artifacts: "host/nxdt_host.7z"
          token: ${{ secrets.GITHUB_TOKEN }}
